# Generated by Django 3.0.2 on 2020-01-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], max_length=1),
        ),
    ]
