# Generated by Django 3.0.2 on 2020-01-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0005_auto_20200109_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complement',
            name='to_comment',
        ),
    ]
