# Generated by Django 3.0.2 on 2020-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0006_remove_complement_to_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complement',
            old_name='username',
            new_name='from_user',
        ),
    ]
