# Generated by Django 3.0.2 on 2020-01-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0007_auto_20200109_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='complement',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registrants.UserProfile'),
            preserve_default=False,
        ),
    ]
