# Generated by Django 3.0.2 on 2020-01-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0008_complement_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complement',
            name='to_user',
        ),
    ]
