# Generated by Django 3.0.2 on 2020-01-09 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrants', '0009_remove_complement_to_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complement',
            new_name='UserPost',
        ),
    ]
