# Generated by Django 3.0.2 on 2020-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0011_auto_20200110_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
